### ISSUE TITLE
It doesnt work, pls help!

### ISSUE THREAD

**Issue by byNikolai** [AnthonyMonette/TheWitcherTRPG#308]
I tryed to install the system on 3 versions of Foundry (9,10,11) but it just doesnt want to work, I cant even find it in official list of systems. Please help me. The Error is following:

Error: The request to https://github.com/AnthonyMonette/TheWitcherTRPG.git did not provide a valid manifest file.
    at Function.getManifest (file:///C:/Users/By_Nickolay/foundry9/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7135)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async checkPackage (file:///C:/Users/By_Nickolay/foundry9/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1295)
    at async Module.installPackage (file:///C:/Users/By_Nickolay/foundry9/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3053)
    at async SetupView.handlePost (file:///C:/Users/By_Nickolay/foundry9/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1757)

**Comment by ortegamarcel** [comment]
Looks like you entered the wrong manifest URL. Try this one: `https://github.com/AnthonyMonette/TheWitcherTRPG/releases/latest/download/system.json`

**Comment by byNikolai** [comment]
> https://github.com/AnthonyMonette/TheWitcherTRPG/releases/latest/download/system.json

now it is throwing this (foundry 9). I`ve also tryed to put system manualy but nothig happend. Foundry cant see it.

setup.js:265 ReferenceError: k is not defined
    at Function.getManifest (file:///C:/Users/By_Nickolay/foundry9/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7288)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async checkPackage (file:///C:/Users/By_Nickolay/foundry9/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1295)
    at async Module.installPackage (file:///C:/Users/By_Nickolay/foundry9/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3053)
    at async SetupView.handlePost (file:///C:/Users/By_Nickolay/foundry9/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1757)

**Comment by Melkkart** [comment]
Try version 10, Build 291, Stable, and install the system from the link ortegamarcel said.

**Comment by AnthonyMonette** [comment]
@byNikolai could you confirm if the latest version works fine with V11?
https://github.com/AnthonyMonette/TheWitcherTRPG/releases/latest/download/system.json

**Comment by AetheriMC** [comment]
Foundry VTT v11 - Build 309

When attempting to install the module, this error is shown

![image](https://github.com/AnthonyMonette/TheWitcherTRPG/assets/64112227/af0e8f0c-f9b4-4229-bd16-1a9d5ffa41b8)
